# -*- coding: utf-8 -*-
"""ContentBasedV3.ipynb

Automatically generated by Colab.

Original file is located at
 https://colab.research.google.com/drive/1Uy5Pu0mHSVgjCVG0OOkO49mc0RetIiTy

# Content-Based Recommender V3

**Mudanças em relação à V2:**
- Removida concatenação de matrizes ponderadas (causava poluição entre features)
- Score final = **soma de scores independentes** com peso fixo por feature
- **Gênero musical** derivado via KMeans (20 clusters) sobre features de áudio
- Grid search automático sobre combinações de features → CSV de resultados
- Kernel Gaussiano para proximidade de ano (contínuo, não binário)

**Arquitetura do score:**
```
score(q, c) = w_audio * sim_cosseno(q, c) # contínuo [0,1]
 + w_genero * (cluster_q == cluster_c) # binário
 + w_artista* (artista_q == artista_c) # binário
 + w_ano * exp(-0.5 * ((ano_q - ano_c)/σ)²) # Gaussiano [0,1]
 + w_era * (era_q == era_c) # binário
 + w_pais * (pais_q == pais_c) # binário
```

## 1. Imports
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics.pairwise import cosine_similarity
from itertools import product
import glob, os, json as _json
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

AUDIO_FEATURES = [
 'danceability', 'energy', 'valence', 'tempo',
 'instrumentalness', 'liveness', 'loudness',
 'speechiness', 'key', 'mode'
]

N_GENRE_CLUSTERS = 20 # clusters KMeans para gênero
SIGMA_ANO = 15 # desvio padrão do kernel Gaussiano (anos)

print("OK")

# # Faz o download do dataset
# !kaggle datasets download -d himanshuwagh/spotify-million

# # Cria uma pasta e extrai os ficheiros lá para dentro de forma silenciosa (-q)
# !mkdir -p dataset_spotify
# !unzip -q spotify-million.zip -d dataset_spotify
# print("Dataset descarregado e extraído para a pasta 'dataset_spotify'!")

"""## 2. Carregamento e Feature Engineering"""

# CSV_PATH = 'audio_features.csv'

# df_raw = pd.read_csv(CSV_PATH, dtype={
# 'uri':str,'id':str,'nome':str,'artista':str,'isrc':str
# })
# df = df_raw.dropna(subset=AUDIO_FEATURES).reset_index(drop=True)
# print(f"Dataset: {len(df):,} músicas com features de áudio")

# Ano e Era via ISRC
def isrc_para_ano(isrc):
 try:
 s = str(isrc).strip().replace('-', '')
 if len(s) < 7: return np.nan
 yy = int(s[5:7])
 return 2000 + yy if yy <= 25 else 1900 + yy
 except:
 return np.nan

anos = df['isrc'].apply(isrc_para_ano)
df['ano'] = anos.fillna(anos.median())

def era_musical(ano):
 if ano < 1970: return 'pre_70'
 elif ano < 1980: return 'anos_70'
 elif ano < 1990: return 'anos_80'
 elif ano < 2000: return 'anos_90'
 elif ano < 2010: return 'anos_2000'
 elif ano < 2020: return 'anos_2010'
 else: return 'anos_2020'

df['era'] = df['ano'].apply(era_musical)
print(f"Ano: {int(df['ano'].min())} – {int(df['ano'].max())} | sem ISRC: {anos.isna().sum():,}")

# País via ISRC
df['pais_isrc'] = df['isrc'].str[:2].str.upper().fillna('XX')
paises_validos = df['pais_isrc'].value_counts()[lambda x: x >= len(df) * 0.001].index
df['pais_isrc'] = df['pais_isrc'].where(df['pais_isrc'].isin(paises_validos), 'OUTRO')
print(f"Países ISRC: {df['pais_isrc'].nunique()} grupos")

import json

# Gênero Musical via API do Last.fm
print("Carregando gêneros oficiais do Last.fm...")

try:
 with open('generos_lastfm.json', 'r', encoding='utf-8') as f:
 mapa_generos = json.load(f)
except FileNotFoundError:
 print(" Arquivo 'generos_lastfm.json' não encontrado. Certifique-se de que ele está na mesma pasta.")
 mapa_generos = {}

# Mapeia a lista de gêneros para cada música baseada no nome do artista
# Se o artista não estiver no JSON, ele recebe uma lista vazia []
df['genero_lista'] = df['artista'].map(lambda a: mapa_generos.get(a, []))

# Mostra alguns exemplos para validar
print("\nExemplos de mapeamento:")
print(df[['nome', 'artista', 'genero_lista']].head(5))

from sklearn.preprocessing import StandardScaler

print("Padronizando matriz de features de áudio...")

# Verifica se o dataset possui as colunas de áudio antes de tentar padronizar
if all(col in df.columns for col in AUDIO_FEATURES):
 scaler_audio = StandardScaler()
 mat_audio_std = scaler_audio.fit_transform(df[AUDIO_FEATURES]).astype(np.float32)
else:
 print("As colunas de áudio não foram encontradas no DataFrame.")

"""## 3. Funções de Score Individuais

Cada função recebe o índice da música alvo e retorna um array `(N,)` em `[0, 1]`.

"""

# Modifique a célula onde as funções de score são definidas (Seção 3)

def get_mat_audio(features_ativas: list) -> np.ndarray:
 """Gera a matriz normalizada em L2 apenas para o subconjunto de features desejado."""
 if not features_ativas:
 return np.zeros((len(df), 0), dtype=np.float32)

 idx_cols = [AUDIO_FEATURES.index(f) for f in features_ativas]
 sub_mat = mat_audio_std[:, idx_cols]

 normas = np.linalg.norm(sub_mat, axis=1, keepdims=True)
 normas[normas == 0] = 1
 return sub_mat / normas

def score_audio(idx: int, mat_audio: np.ndarray) -> np.ndarray:
 """Cosine similarity dinâmico. Aceita a matriz gerada por get_mat_audio."""
 if mat_audio.shape[1] == 0:
 return np.zeros(mat_audio.shape[0], dtype=np.float32)
 s = cosine_similarity(mat_audio[idx:idx+1], mat_audio).flatten()
 return np.clip((s + 1) / 2, 0, 1)


def score_genero(idx: int) -> np.ndarray:
 """
 Calcula a similaridade de Jaccard entre as listas de gêneros do Last.fm.
 Retorna 1.0 para matches perfeitos, fracionados para matches parciais e 0.0 sem match.
 """
 generos_alvo = set(df.loc[idx, 'genero_lista'])

 # Se a música alvo não tem gênero mapeado, retorna zero para todas
 if not generos_alvo:
 return np.zeros(len(df), dtype=np.float32)

 scores = np.zeros(len(df), dtype=np.float32)

 # Loop rápido pelas listas de gêneros
 for i, lista_cand in enumerate(df['genero_lista']):
 set_cand = set(lista_cand)
 if not set_cand:
 continue

 intersecao = len(generos_alvo.intersection(set_cand))
 uniao = len(generos_alvo.union(set_cand))

 scores[i] = intersecao / uniao if uniao > 0 else 0.0

 return scores

def score_artista(idx: int) -> np.ndarray:
 """1.0 se mesmo artista, 0.0 caso contrário."""
 a = df.loc[idx, 'artista']
 return (df['artista'].values == a).astype(np.float32)

def score_ano(idx: int, sigma: float = SIGMA_ANO) -> np.ndarray:
 """Kernel Gaussiano: 1.0 no mesmo ano, cai conforme a distância aumenta.
 σ=15 → ±15 anos ≈ 0.61 | ±30 anos ≈ 0.14"""
 ano_alvo = df.loc[idx, 'ano']
 return np.exp(-0.5 * ((df['ano'].values - ano_alvo) / sigma) ** 2).astype(np.float32)

def score_era(idx: int) -> np.ndarray:
 """1.0 se mesma era (décade), 0.0 caso contrário."""
 e = df.loc[idx, 'era']
 return (df['era'].values == e).astype(np.float32)

def score_pais(idx: int) -> np.ndarray:
 """1.0 se mesmo país de origem ISRC, 0.0 caso contrário."""
 p = df.loc[idx, 'pais_isrc']
 return (df['pais_isrc'].values == p).astype(np.float32)

SCORE_FUNCS = {
 'audio': score_audio,
 'genero': score_genero,
 'artista': score_artista,
 'ano': score_ano,
 'era': score_era,
 'pais': score_pais,
}

print("Score functions:", list(SCORE_FUNCS.keys()))

"""## 4. Recomendador"""

def recomendar(
 nome_musica: str,
 pesos: dict,
 audio_features_ativas: list = AUDIO_FEATURES, # Novidade
 top_k: int = 20,
 excluir_mesmo_artista: bool = False,
) -> pd.DataFrame:

 mascara = df['nome'].str.lower().str.contains(nome_musica.lower(), na=False)
 if not mascara.any():
 print(f"'{nome_musica}' não encontrada."); return pd.DataFrame()

 idx_alvo = df[mascara].index[0]
 row_alvo = df.loc[idx_alvo]

 total = sum(v for v in pesos.values() if v > 0)
 pesos_norm = {k: v / total for k, v in pesos.items() if v > 0}

 # Calcula a matriz dinâmica de áudio
 mat_audio = get_mat_audio(audio_features_ativas)

 score = np.zeros(len(df), dtype=np.float32)
 for feat, peso in pesos_norm.items():
 if feat == 'audio':
 score += peso * score_audio(idx_alvo, mat_audio)
 else:
 score += peso * SCORE_FUNCS[feat](idx_alvo)

 score[idx_alvo] = -1
 if excluir_mesmo_artista:
 score[df['artista'].values == row_alvo['artista']] = -1

 top_idx = np.argsort(score)[::-1][:top_k]
 # Removemos 'genero_cluster' e adicionamos 'genero_lista'
 resultado = df.loc[top_idx, ['nome','artista','ano','era','genero_lista','pais_isrc']].copy()

 # Formata a lista para o DataFrame não ficar bagunçado visualmente (mostra só os 3 primeiros)
 resultado['genero_lista'] = resultado['genero_lista'].apply(lambda x: ", ".join(x[:3]) if isinstance(x, list) and x else "N/A")
 resultado.insert(len(resultado.columns), 'score', score[top_idx].round(4))
 resultado['ano'] = resultado['ano'].astype(int)

 return resultado.reset_index(drop=True)

print("recomendar() pronta.")

"""## 5. Exemplos"""

# Configuração balanceada: áudio como base, gênero filtra perfil sonoro,
# ano penaliza diferenças temporais
PESOS_DEFAULT = {'audio': 0.70, 'genero': 0.20, 'ano': 0.10}

r = recomendar("Billie Jean", PESOS_DEFAULT, top_k=20, excluir_mesmo_artista=True)
print(r.to_string(index=False))

# Modo "mesma vibe": prioriza características sonoras, ignora ano
r = recomendar("Billie Jean", {'audio': 0.80, 'genero': 0.20}, top_k=15, excluir_mesmo_artista=True)
print(r.to_string(index=False))

"""## 6. Ground Truth — Co-ocorrência em Playlists"""

PASTA_JSON = './dataset_spotify' # ajuste o caminho se necessário

arquivos_json = glob.glob(os.path.join(PASTA_JSON, '**', '*.json'), recursive=True)
print(f"{len(arquivos_json)} arquivos JSON")

track_playlists: dict = {}
for arq in tqdm(arquivos_json, desc="Indexando"):
 with open(arq, encoding='utf-8') as f:
 try: data = _json.load(f)
 except: continue
 for pl in data.get('playlists', []):
 pid = pl['pid']
 for t in pl.get('tracks', []):
 track_playlists.setdefault(t['track_uri'], set()).add(pid)

print(f"Índice: {len(track_playlists):,} URIs únicas")

"""## 7. Métricas"""

def precision_at_k(top_uris, relevantes, k):
 return sum(1 for u in top_uris[:k] if u in relevantes) / k if k else 0.0

def recall_at_k(top_uris, relevantes, k):
 if not relevantes: return 0.0
 return len(set(top_uris[:k]) & relevantes) / len(relevantes)

def ndcg_at_k(top_uris, relevantes, k):
 dcg = sum(1.0 / np.log2(i + 2) for i, u in enumerate(top_uris[:k]) if u in relevantes)
 idcg = sum(1.0 / np.log2(i + 2) for i in range(min(len(relevantes), k)))
 return dcg / idcg if idcg > 0 else 0.0

def get_coocorrencias(uri_alvo, index_pl, uri_series, min_cooc=2):
 pls = index_pl.get(uri_alvo, set())
 if not pls: return set()
 return {u for u in uri_series if u != uri_alvo
 and len(pls & index_pl.get(u, set())) >= min_cooc}

print("Métricas prontas.")

"""## 8. Grid Search — Melhor Combinação de Features

Testa sistematicamente todas as combinações de pesos definidas em `GRID_PESOS`.
Salva tudo em `grid_search_features.csv` para análise offline.

"""

# Parâmetros
# Peso fixo = 1/n_features_ativas (distribuição uniforme)
# Teste binário: cada feature está ON (1) ou OFF (0)

ALL_FEATURES = ['audio', 'genero', 'artista', 'ano', 'era', 'pais']

K_VALUES = [5, 10, 20]
N_AMOSTRAS = 300 # músicas avaliadas por combinação
MIN_PLAYLISTS = 50 # mínimo de playlists para a música ser elegível
MIN_COOC = 2 # co-ocorrências para considerar "relevante"
OUTPUT_CSV = 'feature_selection.csv'
SEED = 42

# Amostra fixa (mesma para todas as combinações → comparação justa)
uri_set = set(track_playlists.keys())
df_elegivel = df[
 df['uri'].isin(uri_set) &
 df['uri'].map(lambda u: len(track_playlists.get(u, set())) >= MIN_PLAYLISTS)
].copy()

amostra = df_elegivel.sample(n=min(N_AMOSTRAS, len(df_elegivel)), random_state=SEED)

# Gera todas as combinações binárias (2^6 = 64)
# Exige que pelo menos 'audio' ou 'genero' esteja ativo (sem sinal sonoro = inválido)
from itertools import product as iproduct

combinacoes = []
for bits in iproduct([0, 1], repeat=len(ALL_FEATURES)):
 config = dict(zip(ALL_FEATURES, bits))
 if config['audio'] == 0 and config['genero'] == 0:
 continue # sem sinal sonoro, descarta
 if sum(bits) == 0:
 continue
 combinacoes.append(config)

print(f"Músicas elegíveis : {len(df_elegivel):,}")
print(f"Amostra : {len(amostra):,}")
print(f"Combinações válidas: {len(combinacoes)}")
print()
print("Exemplos:")
for c in combinacoes[:4]:
 ativas = [f for f, v in c.items() if v]
 print(f" {ativas}")

from itertools import product as iproduct
from tqdm import tqdm
import time
import gc # Garbage Collector

K_EVAL = 10
K_VALUES = [5, 10, 20]
uri_series = df['uri'].values

# Pré-computação de Ground Truths
print(" Preparando Ground Truths...")
amostra_idx = amostra.index.values
amostra_uris = amostra['uri'].values

gt_list = [get_coocorrencias(u, track_playlists, df['uri'], MIN_COOC) for u in amostra_uris]
valid_mask = [len(gt) > 0 for gt in gt_list]

amostra_idx_valido = amostra_idx[valid_mask]
gt_valido = [gt for gt in gt_list if len(gt) > 0]
print(f"Músicas avaliadas na amostra (com co-ocorrência): {len(amostra_idx_valido)}\n")


# =====================================================================
# ESTÁGIO 1: ABLATION DAS FEATURES DE ÁUDIO (RAM-FRIENDLY)
# =====================================================================
print(" ESTÁGIO 1: Seleção do melhor conjunto de variáveis acústicas...")

audio_combinations = []
for bits in iproduct([0, 1], repeat=len(AUDIO_FEATURES)):
 if sum(bits) == 0: continue
 audio_combinations.append([AUDIO_FEATURES[i] for i, b in enumerate(bits) if b])

resultados_audio = []

for features_ativas in tqdm(audio_combinations, desc="Áudio Ablation"):
 mat_audio_temp = get_mat_audio(features_ativas)
 acum_ndcg = []

 for i, (idx_alvo, gt) in enumerate(zip(amostra_idx_valido, gt_valido)):
 # Calcula similaridade apenas para a música atual vs base inteira
 # O flatten() garante que seja um array 1D levíssimo
 score = (mat_audio_temp[idx_alvo:idx_alvo+1] @ mat_audio_temp.T).flatten()
 score = np.clip((score + 1) / 2, 0, 1)
 score[idx_alvo] = -1

 idx_part = np.argpartition(score, -K_EVAL)[-K_EVAL:]
 top_idx = idx_part[np.argsort(score[idx_part])[::-1]]
 top_uris = uri_series[top_idx]

 acum_ndcg.append(ndcg_at_k(top_uris, gt, K_EVAL))

 resultados_audio.append({
 'features': '+'.join(features_ativas),
 'n_features': len(features_ativas),
 f'ndcg@{K_EVAL}': np.mean(acum_ndcg) if acum_ndcg else 0.0
 })

 # Limpa memória ativamente a cada ciclo
 del mat_audio_temp
 gc.collect()

df_audio_res = pd.DataFrame(resultados_audio)
best_audio_row = df_audio_res.loc[df_audio_res[f'ndcg@{K_EVAL}'].idxmax()]
BEST_AUDIO_FEATURES = best_audio_row['features'].split('+')

print(f"\n Melhor subconjunto de áudio: [{best_audio_row['features']}] (NDCG@{K_EVAL} = {best_audio_row[f'ndcg@{K_EVAL}']:.5f})\n")


# =====================================================================
# ESTÁGIO 2: INVERSÃO DE LOOP (MÚSICA -> CONFIGURAÇÃO)
# =====================================================================
print(" ESTÁGIO 2: Otimizando metadados contextuais (Loop Invertido)...")

CONTEXT_FEATURES = ['genero', 'artista', 'ano', 'era', 'pais']
mix_combinations = []

for bits in iproduct([0, 1], repeat=len(CONTEXT_FEATURES) + 1):
 config = tuple(zip(['audio'] + CONTEXT_FEATURES, bits)) # Salvo como tupla imutável
 if sum(bits) == 0: continue
 mix_combinations.append(config)

# Prepara a estrutura para acumular métricas por configuração
resultados_mix_dict = {
 config: {k: {'p': [], 'r': [], 'n': []} for k in K_VALUES}
 for config in mix_combinations
}

MAT_AUDIO_OTIMA = get_mat_audio(BEST_AUDIO_FEATURES)
max_k = max(K_VALUES)

# Loop primário: Músicas (Economiza RAM)
for idx_alvo, gt in tqdm(zip(amostra_idx_valido, gt_valido), total=len(amostra_idx_valido), desc="Processando Amostras"):

 # 1. Pré-computa os vetores (1D) apenas para esta música alvo
 score_vetores = {}

 s_audio = (MAT_AUDIO_OTIMA[idx_alvo:idx_alvo+1] @ MAT_AUDIO_OTIMA.T).flatten()
 score_vetores['audio'] = np.clip((s_audio + 1) / 2, 0, 1)

 for feat in CONTEXT_FEATURES:
 score_vetores[feat] = SCORE_FUNCS[feat](idx_alvo)

 # 2. Testa todas as combinações para esta música alvo
 for config in mix_combinations:
 dict_config = dict(config)
 features_ativas = [f for f, v in dict_config.items() if v == 1]
 peso_unitario = 1.0 / len(features_ativas)

 # Soma rápida de arrays 1D (extremamente eficiente)
 combo_scores = np.zeros(len(df), dtype=np.float32)
 for feat in features_ativas:
 combo_scores += score_vetores[feat]

 combo_scores *= peso_unitario
 combo_scores[idx_alvo] = -1

 # Partição rápida
 idx_part = np.argpartition(combo_scores, -max_k)[-max_k:]
 top_idx = idx_part[np.argsort(combo_scores[idx_part])[::-1]]
 top_uris = uri_series[top_idx]

 # Salva métricas
 for k in K_VALUES:
 resultados_mix_dict[config][k]['p'].append(precision_at_k(top_uris, gt, k))
 resultados_mix_dict[config][k]['r'].append(recall_at_k(top_uris, gt, k))
 resultados_mix_dict[config][k]['n'].append(ndcg_at_k(top_uris, gt, k))

# Converte o dicionário de resultados de volta para um DataFrame
linhas_finais = []
for config, metricas in resultados_mix_dict.items():
 linha = dict(config)
 linha['features_ativas'] = '+'.join([f for f, v in linha.items() if v == 1])

 for k in K_VALUES:
 linha[f'precision@{k}'] = np.mean(metricas[k]['p']) if metricas[k]['p'] else 0.0
 linha[f'recall@{k}'] = np.mean(metricas[k]['r']) if metricas[k]['r'] else 0.0
 linha[f'ndcg@{k}'] = np.mean(metricas[k]['n']) if metricas[k]['n'] else 0.0
 linhas_finais.append(linha)

df_mix_res = pd.DataFrame(linhas_finais)
df_mix_res.to_csv(OUTPUT_CSV, index=False)

best_overall = df_mix_res.loc[df_mix_res['ndcg@10'].idxmax()]
print("\n RESULTADO GLOBAL: MELHOR ARQUITETURA ")
print("-" * 50)
print(f"Features Base : {best_overall['features_ativas']}")
print(f"Micro-features : {best_audio_row['features'] if best_overall['audio'] else 'Nenhuma (Áudio desativado)'}")
print(f"NDCG@10 Global : {best_overall['ndcg@10']:.5f}")

"""## 9. Análise dos Resultados"""

df_sel = pd.read_csv(OUTPUT_CSV)

cols_metric = [f'ndcg@{k}' for k in K_VALUES] + [f'precision@{k}' for k in K_VALUES] + [f'recall@{k}' for k in K_VALUES]

print(f"Total combinações testadas: {len(df_sel)}")
print()

# Ranking completo por NDCG@10
print(" Ranking por NDCG@10 ")
cols_show = ['features_ativas', 'n_features', 'ndcg@10', 'precision@10', 'recall@10', 'ndcg@5', 'ndcg@20']
print(df_sel.sort_values('ndcg@10', ascending=False)[cols_show].to_string(index=False))

# Impacto de cada feature: ON vs OFF
# Para cada feature, compara o NDCG@10 médio das combinações onde ela
# está ATIVA versus INATIVA — mantendo as outras features variando.
# Delta positivo = feature ajuda. Delta negativo = feature atrapalha.

print(f"{'Feature':<12} {'ON (média)':>12} {'OFF (média)':>12} {'Delta':>10} Veredicto")
print("-" * 68)

for feat in ALL_FEATURES:
 on = df_sel[df_sel[feat] == 1]['ndcg@10']
 off = df_sel[df_sel[feat] == 0]['ndcg@10']
 delta = on.mean() - off.mean()
 if delta > 0.002: veredicto = " AJUDA"
 elif delta < -0.002: veredicto = " ATRAPALHA"
 else: veredicto = " NEUTRO"
 print(f"{feat:<12} {on.mean():>12.5f} {off.mean():>12.5f} {delta:>+10.5f} {veredicto}")

# Melhor config por nº de features ativas
df_results['n_features'] = (df_results[cols_feat] > 0).sum(axis=1)
print(f"{'N feat':>6} {'NDCG@10':>8} Configuração")
print("-" * 60)
for n in sorted(df_results['n_features'].unique()):
 sub = df_results[df_results['n_features'] == n]
 best = sub.loc[sub['ndcg@10'].idxmax()]
 cfg = ' | '.join(f"{f}={best[f]:.2f}" for f in cols_feat if best[f] > 0)
 print(f"{n:>6} {best['ndcg@10']:>8.5f} {cfg}")

# Melhor combinação por número de features
print(f"{'N feat':>6} {'NDCG@10':>8} Features ativas")
print("-" * 55)
for n in sorted(df_sel['n_features'].unique()):
 sub = df_sel[df_sel['n_features'] == n]
 best = sub.loc[sub['ndcg@10'].idxmax()]
 print(f"{n:>6} {best['ndcg@10']:>8.5f} {best['features_ativas']}")

# Visualizações
import matplotlib.pyplot as plt
import matplotlib; matplotlib.rcParams['figure.dpi'] = 120

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# --- Plot 1: ON vs OFF por feature ---
ax = axes[0]
deltas, labels, cores = [], [], []
for feat in ALL_FEATURES:
 d = df_sel[df_sel[feat] == 1]['ndcg@10'].mean() - df_sel[df_sel[feat] == 0]['ndcg@10'].mean()
 deltas.append(d)
 labels.append(feat)
 cores.append('#55A868' if d > 0.002 else '#C44E52' if d < -0.002 else '#8C8C8C')

bars = ax.barh(labels, deltas, color=cores, alpha=0.85)
ax.axvline(0, color='black', lw=0.8, ls='--')
for b, v in zip(bars, deltas):
 ax.text(v + (0.0002 if v >= 0 else -0.0002), b.get_y() + b.get_height()/2,
 f"{v:+.4f}", va='center', ha='left' if v >= 0 else 'right', fontsize=8)
ax.set_xlabel("Delta NDCG@10 (ON − OFF)")
ax.set_title("Impacto de cada feature
(verde=ajuda | cinza=neutro | vermelho=atrapalha)")

# --- Plot 2: NDCG@10 por número de features ativas ---
ax = axes[1]
medias = df_sel.groupby('n_features')['ndcg@10'].agg(['mean','max','min'])
x = medias.index.tolist()
ax.plot(x, medias['max'], marker='o', label='melhor combo', color='#4C72B0', lw=2)
ax.plot(x, medias['mean'], marker='s', label='média combos', color='#DD8452', lw=1.5, ls='--')
ax.plot(x, medias['min'], marker='^', label='pior combo', color='#C44E52', lw=1, ls=':')
ax.set_xlabel("Número de features ativas")
ax.set_ylabel("NDCG@10")
ax.set_title("NDCG@10 por quantidade de features")
ax.legend()
ax.grid(True, alpha=0.3)
ax.set_xticks(x)

plt.tight_layout()
plt.savefig('feature_selection.png', bbox_inches='tight')
plt.show()
print("Salvo em feature_selection.png")

# Aplicar a melhor combinação encontrada
best_row = df_sel.loc[df_sel['ndcg@10'].idxmax()]
features_best = best_row['features_ativas'].split('+')

print("=" * 60)
print("MELHOR COMBINAÇÃO DE FEATURES")
print("=" * 60)
print(f" Features ativas : {best_row['features_ativas']}")
print(f" N features : {int(best_row['n_features'])}")
print(f" NDCG@5 : {best_row['ndcg@5']:.5f}")
print(f" NDCG@10 : {best_row['ndcg@10']:.5f}")
print(f" NDCG@20 : {best_row['ndcg@20']:.5f}")
print(f" Precision@10 : {best_row['precision@10']:.5f}")
print(f" Recall@10 : {best_row['recall@10']:.5f}")
print("=" * 60)

# Peso uniforme entre as features ativas
pesos_best = {f: 1.0 for f in features_best}

print()
r = recomendar("Billie Jean", pesos_best, top_k=20, excluir_mesmo_artista=True)
print(r.to_string(index=False))
